# Informa a docker sobre los contenedores que se quieren "levantar".
version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.mongodb.address=:27017
      - --certificatesresolvers.default.acme.tlschallenge=true
      - --certificatesresolvers.default.acme.email=tuemail@ejemplo.com
      - --certificatesresolvers.default.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "27017:27017"
    labels: 
       - "traefik.enable=true"
       - "traefik.http.routers.api.rule=Host(`traefik.universidad.localhost`)"
       - "traefik.http.routers.api.service=api@internal"
       - "traefik.http.routers.api.entrypoints=websecure"
       - "traefik.http.routers.api.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
      - ./letsencrypt:/letsencrypt
    networks:
      - pdf-extractext-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: pdf-extractext:1.0.1
    container_name: pdf-extractext
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs:ro
      - ./letsencrypt:/letsencrypt
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - pdf-extractext-network
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`universidad.localhost`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=8000"

  mongodb:
    image: mongo:7-jammy
    container_name: pdf-extractext-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db
    networks:
      - pdf-extractext-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mongo.rule=HostSNI(`mongo-express.universidad.localhost`)"
      - "traefik.tcp.routers.mongo.entrypoints=mongodb"
      - "traefik.tcp.routers.mongo.tls=true"
      - "traefik.tcp.services.mongo.loadbalancer.server.port=27017"

volumes:
  mongodb_data:

networks:
  pdf-extractext-network:
    driver: bridge
