PDF_REPEATED = "El PDF ya se encuentra repetido en la base de datos."
PDF_UPLOADED = "PDF subido correctamente"
PDF_UPDATED = "PDF actualizado correctamente"
PDF_NOT_FOUND = "PDF no encontrado"
PDF_LIST_SUCCESS = "Lista de PDFs obtenida correctamente"
PDF_GET_ERROR = "Error al obtener los PDFs"
PDF_PROCESS_ERROR = "Error al procesar PDF"
